
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://xx:123@localhost:8761/eureka/
#      defaultZone: http://10.1.66.5:8761/eureka/,http://10.8.4.177:8761/eureka/,http://10.8.4.178:8761/eureka/
    instance:
#      leaseRenewalIntervalInSeconds: 1
#      leaseExpirationDurationInSeconds: 2
      ip-address: true
server:
  port: 8762
spring:
  application:
    name: service-user
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 3.0