eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://xx:123@192.168.17.94:8761/eureka/
#      defaultZone: http://10.1.66.5:8761/eureka/,http://10.8.4.177:8761/eureka/,http://10.8.4.178:8761/eureka/
    instance:
#      leaseRenewalIntervalInSeconds: 1
#      leaseExpirationDurationInSeconds: 2
      ip-address: true
server:
  port: 8763
spring:
  datasource:
    url: jdbc:mysql://192.168.17.92:3306/springcloud?useUnicode=true&amp;amp;characterEncoding=UTF-8
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-user
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 3.0